import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchPublicPosts } from '../services/api';
import PostCard from '../components/PostCard';
import {
  Camera,
  UploadCloud,
  FileCheck2,
  Calendar,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  FileText
} from 'lucide-react';

const Home = () => {
  const [recentPosts, setRecentPosts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadRecentPosts = async () => {
      try {
        const data = await fetchPublicPosts({ limit: 4, sort: 'newest' });
        if (data.success) {
          setRecentPosts(data.posts || []);
        }
      } catch (err) {
        console.error('Error loading home posts:', err);
      } finally {
        setLoading(false);
      }
    };

    loadRecentPosts();
  }, []);

  return (
    <div className="space-y-20 pb-16">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-12 sm:pt-20 pb-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-indigo-50/70 via-white to-slate-50 border-b border-slate-200/60">
        <div className="max-w-5xl mx-auto text-center space-y-6">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand-100/80 text-brand-800 text-xs font-semibold tracking-wide border border-brand-200 shadow-xs animate-fadeIn">
            <Sparkles className="w-3.5 h-3.5 text-brand-600" />
            <span>Digital Activity Journal & Public Documentation Gallery</span>
          </div>

          <h1 className="text-4xl sm:text-6xl lg:text-7xl font-extrabold font-display tracking-tight text-slate-900 leading-[1.1]">
            Share Your <span className="bg-gradient-to-r from-brand-600 to-indigo-600 bg-clip-text text-transparent">Moments</span>
          </h1>

          <p className="max-w-2xl mx-auto text-lg sm:text-xl text-slate-600 font-normal leading-relaxed">
            Create, document and preserve photographs with their stories. Designed for institutional events,
            cultural programs, research field trips, and public community archives.
          </p>

          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              to="/gallery"
              className="w-full sm:w-auto px-8 py-4 rounded-xl bg-brand-600 text-white font-semibold shadow-lg shadow-brand-500/25 hover:bg-brand-700 hover:shadow-xl hover:-translate-y-0.5 transition-all text-center flex items-center justify-center gap-2"
            >
              <span>EXPLORE GALLERY</span>
              <ArrowRight className="w-4 h-4" />
            </Link>

            <Link
              to="/create-post"
              className="w-full sm:w-auto px-8 py-4 rounded-xl bg-white text-slate-800 border border-slate-300 font-semibold shadow-xs hover:bg-slate-50 hover:border-slate-400 hover:-translate-y-0.5 transition-all text-center flex items-center justify-center gap-2"
            >
              <UploadCloud className="w-4 h-4 text-brand-600" />
              <span>UPLOAD PHOTOS</span>
            </Link>
          </div>
        </div>

        {/* Feature Highlights Grid */}
        <div className="max-w-6xl mx-auto mt-16 grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white/80 backdrop-blur-xs p-6 rounded-2xl border border-slate-200/80 shadow-xs hover:shadow-md transition-shadow">
            <div className="w-12 h-12 rounded-xl bg-brand-50 text-brand-600 flex items-center justify-center mb-4">
              <Calendar className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-1">
              Backend Timestamps
            </h3>
            <p className="text-sm text-slate-600 leading-relaxed">
              Every post is permanently stamped with UTC upload time generated by the database for tamper-proof chronological accuracy.
            </p>
          </div>

          <div className="bg-white/80 backdrop-blur-xs p-6 rounded-2xl border border-slate-200/80 shadow-xs hover:shadow-md transition-shadow">
            <div className="w-12 h-12 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center mb-4">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-1">
              Admin Moderation
            </h3>
            <p className="text-sm text-slate-600 leading-relaxed">
              Submissions undergo an approval pipeline before publishing publicly, guaranteeing quality and integrity.
            </p>
          </div>

          <div className="bg-white/80 backdrop-blur-xs p-6 rounded-2xl border border-slate-200/80 shadow-xs hover:shadow-md transition-shadow">
            <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center mb-4">
              <FileText className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-1">
              Word (.docx) Reports
            </h3>
            <p className="text-sm text-slate-600 leading-relaxed">
              Generate formatted official Word documentation reports instantly with embedded photographs and live gallery links.
            </p>
          </div>
        </div>
      </section>

      {/* Recent Approved Posts Showcase */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between mb-8 gap-4">
          <div>
            <span className="text-xs uppercase tracking-wider font-bold text-brand-600">
              Live Documentation Stream
            </span>
            <h2 className="text-3xl font-bold font-display text-slate-900 tracking-tight mt-1">
              Recent Documentation Posts
            </h2>
            <p className="text-slate-600 text-sm mt-1">
              Browse the latest public community uploads and verified event logs.
            </p>
          </div>

          <Link
            to="/gallery"
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-brand-600 hover:text-brand-700 group"
          >
            <span>View All in Chronological Gallery</span>
            <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </Link>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {[1, 2].map((i) => (
              <div key={i} className="bg-white rounded-2xl border border-slate-200 p-6 animate-pulse space-y-4">
                <div className="h-7 bg-slate-200 rounded-md w-3/4" />
                <div className="h-4 bg-slate-200 rounded-md w-full" />
                <div className="h-4 bg-slate-200 rounded-md w-5/6" />
                <div className="h-48 bg-slate-200 rounded-xl" />
                <div className="h-6 bg-slate-200 rounded-md w-1/2" />
              </div>
            ))}
          </div>
        ) : recentPosts.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {recentPosts.map((post) => (
              <PostCard key={post._id} post={post} />
            ))}
          </div>
        ) : (
          <div className="bg-white p-12 rounded-2xl border border-slate-200 text-center max-w-lg mx-auto">
            <Camera className="w-12 h-12 text-slate-300 mx-auto mb-3" />
            <h3 className="text-lg font-bold text-slate-900">No public posts yet</h3>
            <p className="text-sm text-slate-500 mt-1 mb-6">
              Be the first contributor to document an event or photograph!
            </p>
            <Link
              to="/create-post"
              className="px-6 py-2.5 rounded-lg bg-brand-600 text-white font-medium text-sm hover:bg-brand-700"
            >
              Upload Post
            </Link>
          </div>
        )}
      </section>

      {/* Call to Action Banner */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="relative rounded-3xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-8 sm:p-12 overflow-hidden shadow-2xl">
          <div className="relative z-10 max-w-2xl space-y-4">
            <span className="inline-block px-3 py-1 rounded-full bg-brand-500/20 text-brand-300 text-xs font-semibold tracking-wider uppercase border border-brand-500/30">
              Community Contributions
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold font-display tracking-tight text-white">
              Document your organization's events and milestones
            </h2>
            <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
              Sign up today to create comprehensive photo galleries with high-resolution imagery, automated timestamps, and official Word document reports.
            </p>
            <div className="pt-2 flex flex-wrap gap-4">
              <Link
                to="/register"
                className="px-6 py-3 rounded-xl bg-brand-600 text-white font-semibold hover:bg-brand-500 transition-colors shadow-lg shadow-brand-500/30"
              >
                Create Contributor Account
              </Link>
              <Link
                to="/about"
                className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/20 text-white font-semibold transition-colors border border-white/20"
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
